apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  selector:
    matchLabels:
      name: nodeapp
  replicas: {{ .Values.APP_REPLICAS_COUNT }}
  template:
    metadata:
      labels:
        name: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: 214797541313.dkr.ecr.us-west-2.amazonaws.com/kanikotest:v2
        ports:
          - containerPort: {{ .Values.NODE_APP_PORT }}
        env:
          - name: MYSQL_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: nodeapp-secret
                key: MYSQL_HOSTNAME
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: nodeapp-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nodeapp-secret
                key: MYSQL_PASSWORD

          - name: REDIS_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: nodeapp-secret
                key: REDIS_HOSTNAME
