apiVersion: v1
kind: Secret
metadata:
  name: nodeapp-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_HOSTNAME: ZGI=
  MYSQL_USER: bWluYQ==
  MYSQL_PASSWORD: cm9vdA==
  REDIS_HOSTNAME: cmVkaXM=

  